version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/service-account.json
      - PORT=8080
    volumes:
      - ./service-account.json:/run/secrets/service-account.json:ro
