version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:local
    ports:
      - "8080:8080"
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      PORT: ${PORT}
